<?php

/**
 * @file
 * Stub for Coterie Relationships.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function coterie_relationship_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.coterie_relationship':
            return '<p>' . t('Provides the Relationship entity and UI for Coterie.') . '</p>';
    }
}
